### ISSUE TITLE
Add renovate bot integration for advanced dependency management

### ISSUE THREAD

**Issue by synergiator** [apache/cloudstack-terraform-provider#19]
Like in [this project](https://github.com/firecow/gitlab-ci-local/commit/36dffbb71279703728f824bc86d1750baa14f40f), it would be great to have automatic pull request suggestions from the Renovate Bot. It shall scan for ```go.mod``` entries and find newer versions and then suggest according change sets.

**Comment by harikrishna-patnala** [comment]
Thanks @synergiator for the suggestion, I'll keep this ticket open for tracking so that we can work on it for next release.

Other issue I could see from this is, existing cloudstack terraform provider may not work if the provider SDK is generated with latest terraform versions as it has changed few implementations without backward compatibility. So cloudstack provider will need some rework inorder to generate SDK with latest terraform version.

**Comment by vishesh92** [comment]
We have added dependabot in this PR: https://github.com/apache/cloudstack-terraform-provider/pull/70. It's purpose is same as the renovate bot. Closing this issue.
