### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by CodeBleu** [apache/cloudstack-terraform-provider#85]
I believe this repo has been transferred over to Apache from another owner, and was just curious who is leading the charge of keeping this updated?  I'm assuming @rohityadavcloud  ? :slightly_smiling_face: 

It has been **over 2 years** since the release of `0.4.0` and was wondering when the next release is planned?  I see there is a release of `0.5.0` planned, but no plan date for it.  

Just wondering if instead of trying to directly release `0.5.0` from `0.4.0`, that there could be some smaller releases to get these latest fixes/additions from `main`  into the [ Terraform registry](https://registry.terraform.io/providers/cloudstack/cloudstack/latest) quicker?

There have been some really beneficial changes that have happened in the past 10 months, that would be hugely beneficial to have in an updated release.  Below are 2 big ones ( IMHO ):

- Additional [Data Sources](https://github.com/apache/cloudstack-terraform-provider/pull/38)

- The following  `Resources` as well:
    - "cloudstack_account"
    - "cloudstack_disk_offering"
    - "cloudstack_domain"
    - "cloudstack_kubernetes_cluster"
    - "cloudstack_kubernetes_version"
    - "cloudstack_network_offering"
    - "cloudstack_service_offering"
    - "cloudstack_user"
    - "cloudstack_volume"
    - "cloudstack_zone"

I would prefer not to have to fork and create a new provider in the Terraform registry, but might have to go down that path, sooner than later.   I understand this is OSS, but was hoping that now that its under the control of Apache/ShapeBlue, that it would receive a bit more attention :slightly_smiling_face: 

Any update on this would be greatly appreciated.

**Comment by rohityadavcloud** [comment]
Hi @CodeBleu thanks for the issue and welcome to opensource! To be clear this sub-project and the parent project are only under the control of the ASF and not any specific user or vendor organisation or led by an individual. We're all volunteers working in our 'free' time.

Even though my $dayjob is a lot more aligned to work on CloudStack and related opensource projects, it's not always possible to manage bandwidth equally on all sub-projects. In fact, I was hoping more users and organisations would volunteer (and few of the original ones) would come forward to support this and even maintain this.

Some of us were hoping to work on the 0.5.0 release last year but couldn't find bandwidth due to work on 4.19 and 4.18 maintenance releases and other $dayjob work. That said, I tried to build support internally in my org and our @kiranchavala has expressed interest to lead the release effort in two parts (1) do a faster/interim release with `main` and (2) spend time to work on features and improvements to do a proper release. Ideally, any serious contributor will find support in the community wrt maintenance, releases etc. In fact if you could help us that it would be great!

I hope I've clarified the current state, and will this issue as this was a question.
